//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeoAlvisService.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Track
    {
        public int ID { get; set; }
        public int DiskID { get; set; }
        public string TrackURL { get; set; }
        public string TrackName { get; set; }
        public Nullable<int> ArtistID { get; set; }
        public string ArtistName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Disk Disk { get; set; }
    }
}
