//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeoAlvisService.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YGFLDBEntities : DbContext
    {
        public YGFLDBEntities()
            : base("name=YGFLDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<ApplyMessage> ApplyMessages { get; set; }
        public virtual DbSet<ApplyPosition> ApplyPositions { get; set; }
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistDetail> ArtistDetails { get; set; }
        public virtual DbSet<Disk> Disks { get; set; }
        public virtual DbSet<ProductDetail> ProductDetails { get; set; }
        public virtual DbSet<Show> Shows { get; set; }
        public virtual DbSet<ShowCategory> ShowCategories { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Track> Tracks { get; set; }
        public virtual DbSet<Video> Videos { get; set; }
        public virtual DbSet<VideoServer> VideoServers { get; set; }
    }
}
